# Add PGP key to install mysql 5.7 from mysql repository
- name: Add PGP key
  apt_key:
    keyserver: hkp://pgp.mit.edu:80
    id: 5072E1F5

- name: Add official APT repository
  apt_repository:
    repo: "deb http://repo.mysql.com/apt/debian/ stretch mysql-5.7"

# Install mysql
- name: Install mysql-server
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - mysql-server