--- # apache playbook
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600



- name: add php7.4 apt repository
  apt_repository: 
    repo: 'ppa:ondrej/php' 
    state: present 
    filename: php7.4
    update_cache: yes

- name: 1. install Apache
  apt: name=apache2 state=present

- name: 2. install php module for apache
  apt: name=php7.4 state=present

- name: starting apache
  service: name=apache2 state=started

- name: install hello world php script
  copy: src=index.php dest=/var/www/html/index.html mode=0644

